version: '3'

services:
  app:
    image: node:7
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm i && npm start"
    ports:
      - 80:3000
    environment:
      NODE_ENV: 'development'
